<a href="https://colab.research.google.com/github/MExavierx/-NOVOprojetoMVCASP2405/blob/main/Exclus%C3%A3o_Digital_no_Brasil_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [38]:
import pandas as pd
import matplotlib as mat
import numpy as np


df_renda = pd.read_excel("/content/Renda.xlsx")
df_escolaridade = pd.read_excel("/content/Escolaridade..xlsx")
df_motivos = pd.read_excel("/content/Motivos.xlsx")

Primeira linha, vamos ver quantas linhas e colunas a nossa tabela renda tem

In [39]:
df_renda.shape

(23, 5)

mostra as informações da nossa tabela escolhida, como por exemplo: linhas e colunas, o tipo que ta na tabela - object ou int64 - desse caso a tabela escolhida é renda

In [40]:
df_renda.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 5 columns):
 #   Column                                                                                                                                           Non-Null Count  Dtype
---  ------                                                                                                                                           --------------  -----
 0   Tabela 7414 - Rendimento médio mensal real domiciliar per capita, por situação do domicílio e existência de utilização da Internet no domicílio  9 non-null      object
 1   Unnamed: 1                                                                                                                                       19 non-null     object
 2   Unnamed: 2                                                                                                                                       21 non-null     object
 3   Unnamed: 3                                                                                                                                       19 non-null     object
 4   Unnamed: 4                                                                                                                                       19 non-null     object
dtypes: object(5)
memory usage: 1.0+ KB

Agora vamos ver as primeiras 10 linhas

In [41]:
df_renda.head(10)

,"Tabela 7414 - Rendimento médio mensal real domiciliar per capita, por situação do domicílio e existência de utilização da Internet no domicílio",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,Variável - Rendimento médio mensal real domici...,NaN,NaN,NaN,NaN
1,Brasil e Grande Região,Existência de utilização da Internet no domicílio,Ano x Situação do domicílio,NaN,NaN
2,NaN,NaN,2025,NaN,NaN
3,NaN,NaN,Total,Urbana,Rural
4,Brasil,Total,2280,2420,1242
5,NaN,Havia utilização de internet,2312,2446,1255
6,NaN,Não havia utilização de internet,1316,1412,1102
7,Norte,Total,1586,1727,990
8,NaN,Havia utilização de internet,1619,1741,1028
9,NaN,Não havia utilização de internet,901,1109,767

Ver as 10 últimas linhas

In [42]:
df_renda.tail(10)

,"Tabela 7414 - Rendimento médio mensal real domiciliar per capita, por situação do domicílio e existência de utilização da Internet no domicílio",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
13,Sudeste,Total,2687,2748,1616
14,NaN,Havia utilização de internet,2716,2776,1628
15,NaN,Não havia utilização de internet,1535,1552,1436
16,Sul,Total,2761,2851,2056
17,NaN,Havia utilização de internet,2787,2875,2075
18,NaN,Não havia utilização de internet,1779,1797,1724
19,Centro-Oeste,Total,2699,2756,1911
20,NaN,Havia utilização de internet,2718,2776,1905
21,NaN,Não havia utilização de internet,1700,1654,2114
22,Fonte: IBGE - Pesquisa Nacional por Amostra de...,NaN,NaN,NaN,NaN

Dia 21/07 - voltando a fazer o tratamento dos dados, vamos imprimir as 10 primeiras e a informação da tabela, usando o .head(10) e o .info()

In [43]:
df_renda.head(10)

,"Tabela 7414 - Rendimento médio mensal real domiciliar per capita, por situação do domicílio e existência de utilização da Internet no domicílio",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,Variável - Rendimento médio mensal real domici...,NaN,NaN,NaN,NaN
1,Brasil e Grande Região,Existência de utilização da Internet no domicílio,Ano x Situação do domicílio,NaN,NaN
2,NaN,NaN,2025,NaN,NaN
3,NaN,NaN,Total,Urbana,Rural
4,Brasil,Total,2280,2420,1242
5,NaN,Havia utilização de internet,2312,2446,1255
6,NaN,Não havia utilização de internet,1316,1412,1102
7,Norte,Total,1586,1727,990
8,NaN,Havia utilização de internet,1619,1741,1028
9,NaN,Não havia utilização de internet,901,1109,767

In [44]:
df_renda.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 5 columns):
 #   Column                                                                                                                                           Non-Null Count  Dtype
---  ------                                                                                                                                           --------------  -----
 0   Tabela 7414 - Rendimento médio mensal real domiciliar per capita, por situação do domicílio e existência de utilização da Internet no domicílio  9 non-null      object
 1   Unnamed: 1                                                                                                                                       19 non-null     object
 2   Unnamed: 2                                                                                                                                       21 non-null     object
 3   Unnamed: 3                                                                                                                                       19 non-null     object
 4   Unnamed: 4                                                                                                                                       19 non-null     object
dtypes: object(5)
memory usage: 1.0+ KB

Vamos ver se conseguimos tirar essas linhas com o  título da tabela

In [45]:
df_renda = pd.read_excel("/content/Renda.xlsx", header=4)

In [46]:
df_renda.head()

  Unnamed: 0                        Unnamed: 1   Total  Urbana   Rural
0     Brasil                             Total  2280.0  2420.0  1242.0
1        NaN      Havia utilização de internet  2312.0  2446.0  1255.0
2        NaN  Não havia utilização de internet  1316.0  1412.0  1102.0
3      Norte                             Total  1586.0  1727.0   990.0
4        NaN      Havia utilização de internet  1619.0  1741.0  1028.0

Renomeando as colunas (Unnamed: 0) e (Unnamed:1)

In [47]:
df_renda = df_renda.rename(columns={
    "Unnamed: 0": "Região",
    "Unnamed: 1": "Situação"
})

In [48]:
df_renda.head()

   Região                          Situação   Total  Urbana   Rural
0  Brasil                             Total  2280.0  2420.0  1242.0
1     NaN      Havia utilização de internet  2312.0  2446.0  1255.0
2     NaN  Não havia utilização de internet  1316.0  1412.0  1102.0
3   Norte                             Total  1586.0  1727.0   990.0
4     NaN      Havia utilização de internet  1619.0  1741.0  1028.0

Preenchendo valores NaN

In [49]:
df_renda['Região'] = df_renda["Região"].ffill()

In [50]:
df_renda.head(10)

     Região                          Situação   Total  Urbana   Rural
0    Brasil                             Total  2280.0  2420.0  1242.0
1    Brasil      Havia utilização de internet  2312.0  2446.0  1255.0
2    Brasil  Não havia utilização de internet  1316.0  1412.0  1102.0
3     Norte                             Total  1586.0  1727.0   990.0
4     Norte      Havia utilização de internet  1619.0  1741.0  1028.0
5     Norte  Não havia utilização de internet   901.0  1109.0   767.0
6  Nordeste                             Total  1483.0  1650.0   872.0
7  Nordeste      Havia utilização de internet  1503.0  1670.0   858.0
8  Nordeste  Não havia utilização de internet  1073.0  1108.0  1023.0
9   Sudeste                             Total  2687.0  2748.0  1616.0

In [51]:
df_renda.head()

   Região                          Situação   Total  Urbana   Rural
0  Brasil                             Total  2280.0  2420.0  1242.0
1  Brasil      Havia utilização de internet  2312.0  2446.0  1255.0
2  Brasil  Não havia utilização de internet  1316.0  1412.0  1102.0
3   Norte                             Total  1586.0  1727.0   990.0
4   Norte      Havia utilização de internet  1619.0  1741.0  1028.0

In [52]:
df_renda.tail()

,Região,Situação,Total,Urbana,Rural
14,Sul,Não havia utilização de internet,1779.0,1797.0,1724.0
15,Centro-Oeste,Total,2699.0,2756.0,1911.0
16,Centro-Oeste,Havia utilização de internet,2718.0,2776.0,1905.0
17,Centro-Oeste,Não havia utilização de internet,1700.0,1654.0,2114.0
18,Fonte: IBGE - Pesquisa Nacional por Amostra de...,NaN,NaN,NaN,NaN

In [53]:
df_renda = df_renda.drop(index=18)

In [54]:
df_renda.tail()

          Região                          Situação   Total  Urbana   Rural
13           Sul      Havia utilização de internet  2787.0  2875.0  2075.0
14           Sul  Não havia utilização de internet  1779.0  1797.0  1724.0
15  Centro-Oeste                             Total  2699.0  2756.0  1911.0
16  Centro-Oeste      Havia utilização de internet  2718.0  2776.0  1905.0
17  Centro-Oeste  Não havia utilização de internet  1700.0  1654.0  2114.0

Vamos tratar a tabela Escolaridade agora.

In [55]:
df_escolaridade.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 10 columns):
 #   Column                                                                                                                                                                                      Non-Null Count  Dtype
---  ------                                                                                                                                                                                      --------------  -----
 0   Tabela 9670 - Pessoas de 10 anos ou mais de idade que utilizaram a Internet no período de referência dos últimos três meses, por nível de instrução e frequência de utilização da internet  9 non-null      object
 1   Unnamed: 1                                                                                                                                                                                  31 non-null     object
 2   Unnamed: 2                                                                                                                                                                                  33 non-null     object
 3   Unnamed: 3                                                                                                                                                                                  31 non-null     object
 4   Unnamed: 4                                                                                                                                                                                  31 non-null     object
 5   Unnamed: 5                                                                                                                                                                                  31 non-null     object
 6   Unnamed: 6                                                                                                                                                                                  31 non-null     object
 7   Unnamed: 7                                                                                                                                                                                  31 non-null     object
 8   Unnamed: 8                                                                                                                                                                                  31 non-null     object
 9   Unnamed: 9                                                                                                                                                                                  31 non-null     object
dtypes: object(10)
memory usage: 2.9+ KB

In [56]:
df_escolaridade.shape

(35, 10)

In [57]:
df_escolaridade.head()

,"Tabela 9670 - Pessoas de 10 anos ou mais de idade que utilizaram a Internet no período de referência dos últimos três meses, por nível de instrução e frequência de utilização da internet",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,Variável - Pessoas de 10 anos ou mais de idade...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Brasil e Grande Região,Frequência de utilização da internet,Ano x Nível de instrução,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,Total,Sem instrução,Fundamental incompleto,Fundamental completo,Médio incompleto,Médio completo,Superior incompleto,Superior completo
4,Brasil,Total,168736,3643,44360,12655,12956,54181,9450,31491

In [58]:
df_escolaridade.tail()

,"Tabela 9670 - Pessoas de 10 anos ou mais de idade que utilizaram a Internet no período de referência dos últimos três meses, por nível de instrução e frequência de utilização da internet",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
30,NaN,Todos os dias,13493,254,3258,932,1147,4129,867,2906
31,NaN,5 ou 6 vezes por semana,156,9,65,13,10,36,5,18
32,NaN,De 1 a 4 vezes por semana,206,18,117,14,12,30,2,13
33,NaN,Menos de uma vez por semana,52,6,23,4,3,11,1,5
34,Fonte: IBGE - Pesquisa Nacional por Amostra de...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [98]:
df_escolaridade = pd.read_excel("/content/Escolaridade..xlsx", header=2)

In [60]:
df_escolaridade.head()

,Brasil e Grande Região,Frequência de utilização da internet,Ano x Nível de instrução,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NaN,NaN,2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,Total,Sem instrução,Fundamental incompleto,Fundamental completo,Médio incompleto,Médio completo,Superior incompleto,Superior completo
2,Brasil,Total,168736,3643,44360,12655,12956,54181,9450,31491
3,NaN,Todos os dias,161231,3049,40630,12042,12580,52698,9318,30913
4,NaN,5 ou 6 vezes por semana,3108,175,1322,260,185,756,70,340

In [99]:
df_escolaridade = df_escolaridade.rename(columns={
    "Ano x Nível de instrução": "Total",
    "Unnamed: 3": "Sem instrução",
    "Unnamed: 4": "Fundamental incompleto",
    "Unnamed: 5": "Fundamental completo",
    "Unnamed: 6": "Médio incompleto",
    "Unnamed: 7": "Médio completo",
    "Unnamed: 8": "Superior incompleto",
    "Unnamed: 9": "Superior completo"
})

In [100]:
df_escolaridade.head()

,Brasil e Grande Região,Frequência de utilização da internet,Total,Sem instrução,Fundamental incompleto,Fundamental completo,Médio incompleto,Médio completo,Superior incompleto,Superior completo
0,NaN,NaN,2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,Total,Sem instrução,Fundamental incompleto,Fundamental completo,Médio incompleto,Médio completo,Superior incompleto,Superior completo
2,Brasil,Total,168736,3643,44360,12655,12956,54181,9450,31491
3,NaN,Todos os dias,161231,3049,40630,12042,12580,52698,9318,30913
4,NaN,5 ou 6 vezes por semana,3108,175,1322,260,185,756,70,340

In [102]:
df_escolaridade = df_escolaridade.drop(index=[0,1])

In [103]:
df_escolaridade.head()

,Brasil e Grande Região,Frequência de utilização da internet,Total,Sem instrução,Fundamental incompleto,Fundamental completo,Médio incompleto,Médio completo,Superior incompleto,Superior completo
2,Brasil,Total,168736,3643,44360,12655,12956,54181,9450,31491
3,NaN,Todos os dias,161231,3049,40630,12042,12580,52698,9318,30913
4,NaN,5 ou 6 vezes por semana,3108,175,1322,260,185,756,70,340
5,NaN,De 1 a 4 vezes por semana,3525,298,1959,282,152,596,52,187
6,NaN,Menos de uma vez por semana,872,121,448,71,39,130,10,51

In [104]:
df_escolaridade.tail()

,Brasil e Grande Região,Frequência de utilização da internet,Total,Sem instrução,Fundamental incompleto,Fundamental completo,Médio incompleto,Médio completo,Superior incompleto,Superior completo
28,NaN,Todos os dias,13493,254,3258,932,1147,4129,867,2906
29,NaN,5 ou 6 vezes por semana,156,9,65,13,10,36,5,18
30,NaN,De 1 a 4 vezes por semana,206,18,117,14,12,30,2,13
31,NaN,Menos de uma vez por semana,52,6,23,4,3,11,1,5
32,Fonte: IBGE - Pesquisa Nacional por Amostra de...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [107]:
df_escolaridade = df_escolaridade.drop(index=32)

KeyError: '[32] not found in axis'

In [108]:
df_escolaridade.tail()

,Brasil e Grande Região,Frequência de utilização da internet,Total,Sem instrução,Fundamental incompleto,Fundamental completo,Médio incompleto,Médio completo,Superior incompleto,Superior completo
27,Centro-Oeste,Total,13908,287,3462,963,1172,4205,875,2943
28,NaN,Todos os dias,13493,254,3258,932,1147,4129,867,2906
29,NaN,5 ou 6 vezes por semana,156,9,65,13,10,36,5,18
30,NaN,De 1 a 4 vezes por semana,206,18,117,14,12,30,2,13
31,NaN,Menos de uma vez por semana,52,6,23,4,3,11,1,5

In [109]:
df_escolaridade["Brasil e Grande Região"] = (
    df_escolaridade["Brasil e Grande Região"].ffill()
)

In [110]:
df_escolaridade.head(15)

,Brasil e Grande Região,Frequência de utilização da internet,Total,Sem instrução,Fundamental incompleto,Fundamental completo,Médio incompleto,Médio completo,Superior incompleto,Superior completo
2,Brasil,Total,168736,3643,44360,12655,12956,54181,9450,31491
3,Brasil,Todos os dias,161231,3049,40630,12042,12580,52698,9318,30913
4,Brasil,5 ou 6 vezes por semana,3108,175,1322,260,185,756,70,340
5,Brasil,De 1 a 4 vezes por semana,3525,298,1959,282,152,596,52,187
6,Brasil,Menos de uma vez por semana,872,121,448,71,39,130,10,51
7,Norte,Total,13988,370,4048,1052,1256,4558,790,1914
8,Norte,Todos os dias,12954,288,3520,963,1179,4360,775,1867
9,Norte,5 ou 6 vezes por semana,475,24,203,43,42,120,10,33
10,Norte,De 1 a 4 vezes por semana,448,36,260,38,29,66,4,14
11,Norte,Menos de uma vez por semana,112,22,64,7,6,11,0,1
12,Nordeste,Total,43955,1653,13728,3126,3622,13983,2053,5790
13,Nordeste,Todos os dias,41832,1361,12601,2987,3519,13633,2032,5699
14,Nordeste,5 ou 6 vezes por semana,873,83,418,66,54,186,13,54
15,Nordeste,De 1 a 4 vezes por semana,1026,152,597,62,41,138,6,32
16,Nordeste,Menos de uma vez por semana,223,57,113,12,8,26,2,6

Tratando a tabela Motivos

In [111]:
df_motivos.shape

(32, 9)

In [71]:
df_motivos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 9 columns):
 #   Column                                                                                                                                                                                                      Non-Null Count  Dtype
---  ------                                                                                                                                                                                                      --------------  -----
 0   Tabela 9661 - Pessoas de 10 anos ou mais de idade que não utilizaram Internet no período de referência dos últimos três meses, por motivo de não terem utilizado a internet (inclui UF) (a partir de 2022)  36 non-null     object
 1   Unnamed: 1                                                                                                                                                                                                  36 non-null     object
 2   Unnamed: 2                                                                                                                                                                                                  34 non-null     object
 3   Unnamed: 3                                                                                                                                                                                                  34 non-null     object
 4   Unnamed: 4                                                                                                                                                                                                  34 non-null     object
 5   Unnamed: 5                                                                                                                                                                                                  34 non-null     object
 6   Unnamed: 6                                                                                                                                                                                                  34 non-null     object
 7   Unnamed: 7                                                                                                                                                                                                  34 non-null     object
 8   Unnamed: 8                                                                                                                                                                                                  34 non-null     object
dtypes: object(9)
memory usage: 2.8+ KB

In [72]:
df_motivos.head()

,"Tabela 9661 - Pessoas de 10 anos ou mais de idade que não utilizaram Internet no período de referência dos últimos três meses, por motivo de não terem utilizado a internet (inclui UF) (a partir de 2022)",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,Variável - Pessoas de 10 anos ou mais de idade...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"Brasil, Grande Região e Unidade da Federação",Ano x Motivo de não terem utilizado a internet,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Total,Serviço de acesso à Internet ou equipamento el...,Serviço de acesso à Internet não estava dispon...,Falta de necessidade,Falta de tempo,Não sabiam utilizar a internet,Preocupação com privacidade ou segurança,Outro motivo
4,Brasil,17697,1600,312,4923,806,7953,935,1168

In [73]:
df_motivos.tail()

,"Tabela 9661 - Pessoas de 10 anos ou mais de idade que não utilizaram Internet no período de referência dos últimos três meses, por motivo de não terem utilizado a internet (inclui UF) (a partir de 2022)",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
33,Mato Grosso do Sul,266,10,4,125,15,82,17,14
34,Mato Grosso,235,26,14,68,18,64,22,22
35,Goiás,364,25,5,83,5,185,38,24
36,Distrito Federal,85,7,0,12,3,39,14,11
37,Fonte: IBGE - Pesquisa Nacional por Amostra de...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [135]:
#df_escolaridade = pd.read_excel("/content/Escolaridade..xlsx", header=2)
df_motivos = pd .read_excel("/content/Motivos.xlsx", header=2)

In [136]:
df_motivos.head()

,"Brasil, Grande Região e Unidade da Federação",Ano x Motivo de não terem utilizado a internet,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,NaN,2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Total,Serviço de acesso à Internet ou equipamento el...,Serviço de acesso à Internet não estava dispon...,Falta de necessidade,Falta de tempo,Não sabiam utilizar a internet,Preocupação com privacidade ou segurança,Outro motivo
2,Brasil,17697,1600,312,4923,806,7953,935,1168
3,Norte,1615,291,51,455,54,579,99,85
4,Nordeste,5695,625,80,1163,84,3154,251,338

In [137]:
df_motivos = df_motivos.rename(columns={
    "Ano x Motivo de não terem utilizado a internet": "Total",
    "Unnamed: 2": "Serviço de acesso à Internet ou equipamento eletrônico necessário era caro",
    "Unnamed: 3": "Serviço de acesso à Internet não estava disponível nos locais que costumavam frequentar",
    "Unnamed: 4": "Falta de necessidade",
    "Unnamed: 5": "Falta de tempo",
    "Unnamed: 6": "Não sabiam utilizar a internet",
    "Unnamed: 7": "Preocupação com privacidade ou segurança",
    "Unnamed: 8": "Outro motivo"
})

In [138]:
df_motivos.head()

,"Brasil, Grande Região e Unidade da Federação",Total,Serviço de acesso à Internet ou equipamento eletrônico necessário era caro,Serviço de acesso à Internet não estava disponível nos locais que costumavam frequentar,Falta de necessidade,Falta de tempo,Não sabiam utilizar a internet,Preocupação com privacidade ou segurança,Outro motivo
0,NaN,2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Total,Serviço de acesso à Internet ou equipamento el...,Serviço de acesso à Internet não estava dispon...,Falta de necessidade,Falta de tempo,Não sabiam utilizar a internet,Preocupação com privacidade ou segurança,Outro motivo
2,Brasil,17697,1600,312,4923,806,7953,935,1168
3,Norte,1615,291,51,455,54,579,99,85
4,Nordeste,5695,625,80,1163,84,3154,251,338

In [139]:
df_motivos = df_motivos.drop(index=[0,1])

In [140]:
df_motivos.head()

,"Brasil, Grande Região e Unidade da Federação",Total,Serviço de acesso à Internet ou equipamento eletrônico necessário era caro,Serviço de acesso à Internet não estava disponível nos locais que costumavam frequentar,Falta de necessidade,Falta de tempo,Não sabiam utilizar a internet,Preocupação com privacidade ou segurança,Outro motivo
2,Brasil,17697,1600,312,4923,806,7953,935,1168
3,Norte,1615,291,51,455,54,579,99,85
4,Nordeste,5695,625,80,1163,84,3154,251,338
5,Sudeste,7161,450,121,2293,520,2863,374,538
6,Sul,2277,168,36,724,108,987,120,135

In [141]:
df_motivos.tail()

,"Brasil, Grande Região e Unidade da Federação",Total,Serviço de acesso à Internet ou equipamento eletrônico necessário era caro,Serviço de acesso à Internet não estava disponível nos locais que costumavam frequentar,Falta de necessidade,Falta de tempo,Não sabiam utilizar a internet,Preocupação com privacidade ou segurança,Outro motivo
31,Mato Grosso do Sul,266,10,4,125,15,82,17,14
32,Mato Grosso,235,26,14,68,18,64,22,22
33,Goiás,364,25,5,83,5,185,38,24
34,Distrito Federal,85,7,0,12,3,39,14,11
35,Fonte: IBGE - Pesquisa Nacional por Amostra de...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [142]:
df_motivos = df_motivos.drop(index=[34])

In [84]:
df_motivos.tail()

,Unnamed: 0,2025,Serviço de acesso à Internet ou equipamento eletrônico necessário era caro,Serviço de acesso à Internet não estava disponível nos locais que costumavam frequentar,Falta de necessidade,Falta de tempo,Não sabiam utilizar a internet,Preocupação com privacidade ou segurança,Outro motivo
29,Rio Grande do Sul,759,57,8,207,13,416,31,28
30,Mato Grosso do Sul,266,10,4,125,15,82,17,14
31,Mato Grosso,235,26,14,68,18,64,22,22
32,Goiás,364,25,5,83,5,185,38,24
33,Distrito Federal,85,7,0,12,3,39,14,11

Vamos verificar os tipos de dados de cada tabela:

In [120]:
df_renda.head()

   Região                          Situação   Total  Urbana   Rural
0  Brasil                             Total  2280.0  2420.0  1242.0
1  Brasil      Havia utilização de internet  2312.0  2446.0  1255.0
2  Brasil  Não havia utilização de internet  1316.0  1412.0  1102.0
3   Norte                             Total  1586.0  1727.0   990.0
4   Norte      Havia utilização de internet  1619.0  1741.0  1028.0

In [121]:
df_renda.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Região    18 non-null     object
 1   Situação  18 non-null     object
 2   Total     18 non-null     float64
 3   Urbana    18 non-null     float64
 4   Rural     18 non-null     float64
dtypes: float64(3), object(2)
memory usage: 852.0+ bytes

In [122]:
df_escolaridade.head()

,Brasil e Grande Região,Frequência de utilização da internet,Total,Sem instrução,Fundamental incompleto,Fundamental completo,Médio incompleto,Médio completo,Superior incompleto,Superior completo
2,Brasil,Total,168736,3643,44360,12655,12956,54181,9450,31491
3,Brasil,Todos os dias,161231,3049,40630,12042,12580,52698,9318,30913
4,Brasil,5 ou 6 vezes por semana,3108,175,1322,260,185,756,70,340
5,Brasil,De 1 a 4 vezes por semana,3525,298,1959,282,152,596,52,187
6,Brasil,Menos de uma vez por semana,872,121,448,71,39,130,10,51

In [128]:
df_escolaridade.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 2 to 31
Data columns (total 10 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Brasil e Grande Região                30 non-null     object
 1   Frequência de utilização da internet  30 non-null     object
 2   Total                                 30 non-null     object
 3   Sem instrução                         30 non-null     object
 4   Fundamental incompleto                30 non-null     object
 5   Fundamental completo                  30 non-null     object
 6   Médio incompleto                      30 non-null     object
 7   Médio completo                        30 non-null     object
 8   Superior incompleto                   30 non-null     object
 9   Superior completo                     30 non-null     object
dtypes: object(10)
memory usage: 2.5+ KB

In [127]:
df_escolaridade["Total"].map(type).value_counts()

Total
<class 'int'>    30
Name: count, dtype: int64

In [129]:
repr(df_escolaridade["Total"].iloc[0])

'168736'

In [130]:
df_escolaridade.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 2 to 31
Data columns (total 10 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Brasil e Grande Região                30 non-null     object
 1   Frequência de utilização da internet  30 non-null     object
 2   Total                                 30 non-null     object
 3   Sem instrução                         30 non-null     object
 4   Fundamental incompleto                30 non-null     object
 5   Fundamental completo                  30 non-null     object
 6   Médio incompleto                      30 non-null     object
 7   Médio completo                        30 non-null     object
 8   Superior incompleto                   30 non-null     object
 9   Superior completo                     30 non-null     object
dtypes: object(10)
memory usage: 2.5+ KB

In [131]:
colunas_numericas = [
    "Total",
    "Sem instrução",
    "Fundamental incompleto",
    "Fundamental completo",
    "Médio incompleto",
    "Médio completo",
    "Superior incompleto",
    "Superior completo"
]

df_escolaridade[colunas_numericas] = (
    df_escolaridade[colunas_numericas]
    .astype(int)
)

In [132]:
df_escolaridade.dtypes

Brasil e Grande Região                  object
Frequência de utilização da internet    object
Total                                    int64
Sem instrução                            int64
Fundamental incompleto                   int64
Fundamental completo                     int64
Médio incompleto                         int64
Médio completo                           int64
Superior incompleto                      int64
Superior completo                        int64
dtype: object

In [133]:
df_motivos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 2 to 33
Data columns (total 9 columns):
 #   Column                                                                                   Non-Null Count  Dtype
---  ------                                                                                   --------------  -----
 0   Unnamed: 0                                                                               32 non-null     object
 1   2025                                                                                     32 non-null     object
 2   Serviço de acesso à Internet ou equipamento eletrônico necessário era caro               32 non-null     object
 3   Serviço de acesso à Internet não estava disponível nos locais que costumavam frequentar  32 non-null     object
 4   Falta de necessidade                                                                     32 non-null     object
 5   Falta de tempo                                                                           32 non-null     object
 6   Não sabiam utilizar a internet                                                           32 non-null     object
 7   Preocupação com privacidade ou segurança                                                 32 non-null     object
 8   Outro motivo                                                                             32 non-null     object
dtypes: object(9)
memory usage: 2.4+ KB

In [143]:
df_motivos.head()

,"Brasil, Grande Região e Unidade da Federação",Total,Serviço de acesso à Internet ou equipamento eletrônico necessário era caro,Serviço de acesso à Internet não estava disponível nos locais que costumavam frequentar,Falta de necessidade,Falta de tempo,Não sabiam utilizar a internet,Preocupação com privacidade ou segurança,Outro motivo
2,Brasil,17697,1600,312,4923,806,7953,935,1168
3,Norte,1615,291,51,455,54,579,99,85
4,Nordeste,5695,625,80,1163,84,3154,251,338
5,Sudeste,7161,450,121,2293,520,2863,374,538
6,Sul,2277,168,36,724,108,987,120,135

In [151]:
df_motivos["Total"].map(type).value_counts()

Total
<class 'int'>    32
Name: count, dtype: int64

In [145]:
repr(df_motivos["Total"].iloc[0])

'17697'

In [148]:
df_motivos = df_motivos.drop(index=35)

In [152]:
df_motivos.info()

<class 'pandas.core.frame.DataFrame'>
Index: 32 entries, 2 to 33
Data columns (total 9 columns):
 #   Column                                                                                   Non-Null Count  Dtype
---  ------                                                                                   --------------  -----
 0   Brasil, Grande Região e Unidade da Federação                                             32 non-null     object
 1   Total                                                                                    32 non-null     object
 2   Serviço de acesso à Internet ou equipamento eletrônico necessário era caro               32 non-null     object
 3   Serviço de acesso à Internet não estava disponível nos locais que costumavam frequentar  32 non-null     object
 4   Falta de necessidade                                                                     32 non-null     object
 5   Falta de tempo                                                                           32 non-null     object
 6   Não sabiam utilizar a internet                                                           32 non-null     object
 7   Preocupação com privacidade ou segurança                                                 32 non-null     object
 8   Outro motivo                                                                             32 non-null     object
dtypes: object(9)
memory usage: 2.5+ KB

In [153]:
colunas_numericas = [
    "Total",
    "Serviço de acesso à Internet ou equipamento eletrônico necessário era caro",
    "Serviço de acesso à Internet não estava disponível nos locais que costumavam frequentar",
    "Falta de necessidade",
    "Não sabiam utilizar a internet",
    "Preocupação com privacidade ou segurança",
    "Outro motivo"
    ]

df_motivos[colunas_numericas] = (
    df_motivos[colunas_numericas]
    .astype(int)
)

In [154]:
df_motivos.info()

<class 'pandas.core.frame.DataFrame'>
Index: 32 entries, 2 to 33
Data columns (total 9 columns):
 #   Column                                                                                   Non-Null Count  Dtype
---  ------                                                                                   --------------  -----
 0   Brasil, Grande Região e Unidade da Federação                                             32 non-null     object
 1   Total                                                                                    32 non-null     int64
 2   Serviço de acesso à Internet ou equipamento eletrônico necessário era caro               32 non-null     int64
 3   Serviço de acesso à Internet não estava disponível nos locais que costumavam frequentar  32 non-null     int64
 4   Falta de necessidade                                                                     32 non-null     int64
 5   Falta de tempo                                                                           32 non-null     object
 6   Não sabiam utilizar a internet                                                           32 non-null     int64
 7   Preocupação com privacidade ou segurança                                                 32 non-null     int64
 8   Outro motivo                                                                             32 non-null     int64
dtypes: int64(7), object(2)
memory usage: 2.5+ KB

In [157]:
df_motivos["Falta de tempo"]

2     806
3      54
4      84
5     520
6     108
7      40
8       3
9       5
10     13
11      1
12     24
13      0
14      9
15     24
16      0
17     18
18      5
19      4
20     15
21      2
22      2
23     13
24     73
25      9
26     13
27    425
28     65
29     30
30     13
31     15
32     18
33      5
Name: Falta de tempo, dtype: object

In [159]:
df_motivos["Falta de tempo"].map(type).value_counts()

Falta de tempo
<class 'int'>    32
Name: count, dtype: int64

In [160]:
df_motivos["Falta de tempo"].unique()

array([806, 54, 84, 520, 108, 40, 3, 5, 13, 1, 24, 0, 9, 18, 4, 15, 2, 73,
       425, 65, 30], dtype=object)

In [161]:
for valor in df_motivos["Falta de tempo"].unique():
  print(repr(valor))

806
54
84
520
108
40
3
5
13
1
24
0
9
18
4
15
2
73
425
65
30

In [164]:
print(df_motivos["Falta de tempo"].dtype)

df_motivos.info()

df_motivos.columns.tolist()

object
<class 'pandas.core.frame.DataFrame'>
Index: 32 entries, 2 to 33
Data columns (total 9 columns):
 #   Column                                                                                   Non-Null Count  Dtype
---  ------                                                                                   --------------  -----
 0   Brasil, Grande Região e Unidade da Federação                                             32 non-null     object
 1   Total                                                                                    32 non-null     int64
 2   Serviço de acesso à Internet ou equipamento eletrônico necessário era caro               32 non-null     int64
 3   Serviço de acesso à Internet não estava disponível nos locais que costumavam frequentar  32 non-null     int64
 4   Falta de necessidade                                                                     32 non-null     int64
 5   Falta de tempo                                                                           32 non-null     object
 6   Não sabiam utilizar a internet                                                           32 non-null     int64
 7   Preocupação com privacidade ou segurança                                                 32 non-null     int64
 8   Outro motivo                                                                             32 non-null     int64
dtypes: int64(7), object(2)
memory usage: 2.5+ KB

['Brasil, Grande Região e Unidade da Federação',
 'Total',
 'Serviço de acesso à Internet ou equipamento eletrônico necessário era caro',
 'Serviço de acesso à Internet não estava disponível nos locais que costumavam frequentar',
 'Falta de necessidade',
 'Falta de tempo',
 'Não sabiam utilizar a internet',
 'Preocupação com privacidade ou segurança',
 'Outro motivo']

In [165]:
df_motivos["Falta de tempo"] = pd.to_numeric(df_motivos["Falta de tempo"])

In [166]:
df_motivos["Falta de tempo"].dtype

dtype('int64')

In [167]:
df_motivos.info()

<class 'pandas.core.frame.DataFrame'>
Index: 32 entries, 2 to 33
Data columns (total 9 columns):
 #   Column                                                                                   Non-Null Count  Dtype
---  ------                                                                                   --------------  -----
 0   Brasil, Grande Região e Unidade da Federação                                             32 non-null     object
 1   Total                                                                                    32 non-null     int64
 2   Serviço de acesso à Internet ou equipamento eletrônico necessário era caro               32 non-null     int64
 3   Serviço de acesso à Internet não estava disponível nos locais que costumavam frequentar  32 non-null     int64
 4   Falta de necessidade                                                                     32 non-null     int64
 5   Falta de tempo                                                                           32 non-null     int64
 6   Não sabiam utilizar a internet                                                           32 non-null     int64
 7   Preocupação com privacidade ou segurança                                                 32 non-null     int64
 8   Outro motivo                                                                             32 non-null     int64
dtypes: int64(8), object(1)
memory usage: 2.5+ KB